### ISSUE TITLE
Problem with fonts

### ISSUE THREAD

**Issue by AdamGerthel** [oddhill/drupal-oddbaby#10]
I'm having path problems with fonts. This is my file structure (simpiflied):

```
/src
  /assets
    /web-symbols
      /css
        web-symbols.css
      /fonts
        web-symbols.eot
        web-symbols.ttf
        etc..
  /scss
    main.scss
    /component
      search-form.scss
```

main.scss:
```
@import 'components/search-form';
```

search-form.scss:
```
@import '../assets/web-symbols/css/web-symbols.css';
```

The paths are all fine, webpack finds the fonts via `web-symbols.css` and the file loader copies them to `fonts` folder, however, the build-versions of the css expects the fonts to be in `css/fonts/<insert font-file>.<extension>` and not `fonts/<insert font-file>.<extension>`

I tried changing the path in the webpack config but that only changed the expected in the build as well so that didn't help.

**Comment by NormySan** [comment]
This should be solved by updating the webpack configuration with the following lines of code.

```
{
  test: /\.(ttf|eot|woff|woff2|svg)$/,
  exclude: /graphics/,
  use: 'file-loader',
  options: {
    name: 'fonts/[name].[ext]',
    publicPath: '../',
  },
},
{
  test: /\.(jpg|png|svg)$/,
  exclude: /fonts/,
  use: 'file-loader',
  options: {
    name: 'graphics/[hash].[ext]',
    publicPath: '../',
  },
},
```

**Comment by AdamGerthel** [comment]
Worked!
