### ISSUE TITLE
Grid

### ISSUE THREAD

**Issue by NormySan** [oddhill/drupal-oddbaby#6]
Oddbaby should come loaded with a pre-defined grid that follows the BME-semantics and has some flexability when it comes to breakpoints and support for both mobile first and desktop first.

Existing grid implementations that are pretty good and could be used as a reference on included with oddbaby:

http://gridle.org/
https://v4-alpha.getbootstrap.com/layout/grid/

**Comment by NormySan** [comment]
After some quick research it looks like gridle might be a good base. Will have to test it out.

http://gridle.org/documentation#advanced-settings-classes-names

**Comment by SebbeLar** [comment]
Found this grid. Haven't had time to test it, but it looks promising.
https://bulma.io/documentation/columns/basics/

**Comment by NormySan** [comment]
Bulma looks cool but I'm more interested in a configurable grid where we can import the SASS and then configure the breakpoints ourselves and get the desired output.

**Comment by NormySan** [comment]
I've added the option for using the bootstrap grid in the next version of the theme.
